# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1278, 902)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(140, 90, 1031, 771))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 6, item)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(540, 50, 221, 41))
        self.lineEdit.setMaxLength(32769)
        self.lineEdit.setObjectName("lineEdit")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "author"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "journal"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "volume"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "number"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "pages"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "year"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "publisher"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "The “mere presence” hypothesis: Investigating the nonverbal effects of cell-phone presence on conversation satisfaction"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "Allred, Ryan J and Crowley, John P"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "Communication Studies"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Form", "68"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("Form", "22--36"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Form", "2017"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("Form", "Taylor \\& Francis"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "Tell me why you’re texting! Effect of cell phone use on interpersonal interactions"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "Avelar, Daniela"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Form", "2015"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "The need to belong: desire for interpersonal attachments as a fundamental human motivation."))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "Baumeister, Roy F and Leary, Mark R"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "Psychological bulletin"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Form", "117"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Form", "497"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "29995"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("Form", "American Psychological Association"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "Not all social exclusions are created equal: Emotional distress following social exclusion is moderated by exclusion paradigm"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "Bernstein, Michael J and Claypool, Heather M"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "Social Influence"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Form", "113--130"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "2012"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("Form", "Taylor \\& Francis"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "Tempted to text: College students’ mobile phone use during a face-to-face interaction with a close friend"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "Brown, Genavee and Manago, Adriana M and Trimble, Joseph E"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "Emerging Adulthood"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Form", "440--443"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "2016"))
        item = self.tableWidget.item(4, 7)
        item.setText(_translate("Form", "Sage Publications Sage CA: Los Angeles, CA"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "The benefits of being present: mindfulness and its role in psychological well-being."))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "Brown, Kirk Warren and Ryan, Richard M}"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "Journal of personality and social psychology"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Form", "84"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Form", "822"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "2003"))
        item = self.tableWidget.item(5, 7)
        item.setText(_translate("Form", "American Psychological Association"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "The effects of divided attention on encoding and retrieval processes in human memory."))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "Craik, Fergus IM and Govoni, Richard and Naveh-Benjamin, Moshe and Anderson, Nicole D"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "Journal of Experimental Psychology: General"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Form", "125"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("Form", "159"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Form", "1996"))
        item = self.tableWidget.item(6, 7)
        item.setText(_translate("Form", "American Psychological Association"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "Flow: The psychology of optimal experience"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "Csikszentmihalyi, Mihaly and Csikzentmihaly, Mihaly"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Form", "1990"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Form", "1990"))
        item = self.tableWidget.item(7, 7)
        item.setText(_translate("Form", "Harper \\& Row New York"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "The experience of boredom: The role of the self-perception of attention."))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Form", "Damrad-Frye, Robin and Laird, James D"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Form", "Journal of Personality and Social Psychology"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Form", "57"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("Form", "315"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Form", "1989"))
        item = self.tableWidget.item(8, 7)
        item.setText(_translate("Form", "American Psychological Association"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "The unengaged mind: Deﬁning boredom in terms of attention\n"
"Mistakenly seeking solitude\n"
"Development and validation of the multidimensional state boredom scale\n"
"Mindfulness and emotion regulation: The development and initial validation of the cognitive and aﬀective mindfulness scale-revised (CAMS-R\n"
"Media multitasking among American youth: Prevalence, predictors, and pairings\n"
"Text messaging reduces analgesic text messaging reduces analgesic requirements during surgery\n"
"Mobile culture in college lectures: Instructors\' and students\' perspectives\n"
"A survey method for characterizing daily life experience: The day reconstruction method\n"
"Exploring parental well-being: Is childcare associated with parental wellbeing and what factors can enhance it\n"
"Put the Phone Down\n"
"“Silence your phones”: Smartphone notiﬁcations increase inattention and hyperactivity symptoms\n"
"Performing high-powered studies eﬃciently with sequential analyses\n"
"The impact of sensory knowledge and attentional focus on pleasure and on behavioral responses to hedonic stimuli\n"
"Social connectedness, dysfunctional interpersonal behaviors, and psychological distress: Testing a mediator model\n"
"It\'s more fun with my phone: A replication study of cell phone presence and task performance\n"
"The cost of interrupted work: More speed and stress\n"
"“Technoference”: The interference of technology in couple relationships and implications for women\'s personal and relational wellbeing\n"
"The iPhone eﬀect: The quality of inperson social interactions in the presence of mobile devices\n"
"Can you connect with me now\n"
"Positive emotion regulation and well-being: Comparing the impact of eight savoring and dampening strategies\n"
"Patterns of mobile device use by caregivers and children during meals in fast food restaurants\n"
"My life has become a major distraction from my cell phone: Partner phubbing and relationship satisfaction among romantic partners\n"
"MLmed: An SPSS macro for multilevel mediation and conditional process analysis\n"
"Connecting alone: Smartphone use, quality of social interactions and well-being (No\n"
"Control and information in the intrapersonal sphere: An extension of cognitive evaluation theory\n"
"Social interactions and well-being: The surprising power of weak ties\n"
"Dimensional models of core aﬀect: A quantitative comparison by means of structural equation modelling\n"
"Heart and mind in conﬂict: The interplay of aﬀect and cognition in consumer decision making\n"
"Mobile phones and the evolution of social behaviour\n"
"A comparison of the cell phone driver and the drunk driver\n"
"Alone together: Why we expect more from technology and less from each other\n"
"Reclaiming conversation: The power of talk in a digital age\n"
"The eﬀect of mobile messaging during a conversation on impression formation and interaction quality\n"
"Examining the impact of oﬀ-task multi-tasking with technology on real-time classroom learning\n"
""))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Form", "Eastwood, John D and Frischen, Alexandra and Fenske, Mark J and Smilek, Daniel"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "Perspectives on Psychological Science"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("Form", "482--495"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Form", "2012"))
        item = self.tableWidget.item(9, 7)
        item.setText(_translate("Form", "Sage Publications Sage CA: Los Angeles, CA"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "Mistakenly seeking solitude"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Form", "Epley, Nicholas and Schroeder, Juliana"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Form", "Journal of Experimental Psychology: General"))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("Form", "143"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(10, 5)
        item.setText(_translate("Form", "1980"))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("Form", "2014"))
        item = self.tableWidget.item(10, 7)
        item.setText(_translate("Form", "American Psychological Association"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "Development and validation of the multidimensional state boredom scale"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Form", "Fahlman, Shelley A and Mercer-Lynn, Kimberley B and Flora, David B and Eastwood, John D"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Form", "Assessment"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("Form", "68--85"))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("Form", "2013"))
        item = self.tableWidget.item(11, 7)
        item.setText(_translate("Form", "Sage Publications Sage CA: Los Angeles, CA"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Form", "Mindfulness and emotion regulation: The development and initial validation of the cognitive and aﬀective mindfulness scale-revised (CAMS-R"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("Form", "Feldman, Greg and Hayes, Adele and Kumar, Sameet and Greeson, Jeff and Laurenceau, Jean-Philippe"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Form", "Journal of psychopathology and Behavioral Assessment"))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(12, 5)
        item.setText(_translate("Form", "177-190"))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("Form", "2007"))
        item = self.tableWidget.item(12, 7)
        item.setText(_translate("Form", "Springer"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Form", "Media multitasking among American youth: Prevalence, predictors, and pairings"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("Form", "Foehr, Ulla G"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Form", "Henry J. Kaiser Family Foundation"))
        item = self.tableWidget.item(13, 6)
        item.setText(_translate("Form", "2006"))
        item = self.tableWidget.item(13, 7)
        item.setText(_translate("Form", "ERIC"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("Form", "Text messaging reduces analgesic text messaging reduces analgesic requirements during surgery"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("Form", "Guillory, Jamie E and Hancock, Jeffrey T and Woodruff, Christopher and Keilman, Jeffrey"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("Form", "Pain Medicine"))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(14, 4)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(14, 5)
        item.setText(_translate("Form", "667--672"))
        item = self.tableWidget.item(14, 6)
        item.setText(_translate("Form", "2015"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("Form", "Mobile culture in college lectures: Instructors\' and students\' perspectives"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("Form", "Hammer, Ronen and Ronen, Miki and Sharon, Amit and Lankry, Tali and Huberman, Yoni and Zamtsov, Victoria"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("Form", "Interdisciplinary Journal of E-Learning and Learning Objects"))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(15, 4)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(15, 5)
        item.setText(_translate("Form", "293--304"))
        item = self.tableWidget.item(15, 6)
        item.setText(_translate("Form", "2010"))
        item = self.tableWidget.item(15, 7)
        item.setText(_translate("Form", "Informing Science Institute"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("Form", "A survey method for characterizing daily life experience: The day reconstruction method"))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("Form", "Kahneman, Daniel and Krueger, Alan B and Schkade, David A and Schwarz, Norbert and Stone, Arthur A"))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("Form", "Science"))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("Form", "306"))
        item = self.tableWidget.item(16, 4)
        item.setText(_translate("Form", "5702"))
        item = self.tableWidget.item(16, 5)
        item.setText(_translate("Form", "1776--1780"))
        item = self.tableWidget.item(16, 6)
        item.setText(_translate("Form", "2004"))
        item = self.tableWidget.item(16, 7)
        item.setText(_translate("Form", "American Association for the Advancement of Science"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("Form", "Exploring parental well-being: Is childcare associated with parental wellbeing and what factors can enhance it"))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("Form", "Kushlev, Kostadin"))
        item = self.tableWidget.item(17, 6)
        item.setText(_translate("Form", "2011"))
        item = self.tableWidget.item(17, 7)
        item.setText(_translate("Form", "University of British Columbia"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("Form", "Put the Phone Down"))
        item = self.tableWidget.item(18, 1)
        item.setText(_translate("Form", "Kushlev, Kostadin and Heintzelman, Samantha J"))
        item = self.tableWidget.item(18, 2)
        item.setText(_translate("Form", "Social Psychological and Personality Science"))
        item = self.tableWidget.item(18, 3)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(18, 4)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(18, 5)
        item.setText(_translate("Form", "702--710"))
        item = self.tableWidget.item(18, 6)
        item.setText(_translate("Form", "2018"))
        item = self.tableWidget.item(18, 7)
        item.setText(_translate("Form", "Sage Publications Sage CA: Los Angeles, CA"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("Form", "“Silence your phones”: Smartphone notiﬁcations increase inattention and hyperactivity symptoms"))
        item = self.tableWidget.item(19, 1)
        item.setText(_translate("Form", "Kushlev, Kostadin and Proulx, Jason and Dunn, Elizabeth W"))
        item = self.tableWidget.item(19, 2)
        item.setText(_translate("Form", "Proceedings of the 2016 CHI conference on human factors in computing systems"))
        item = self.tableWidget.item(19, 5)
        item.setText(_translate("Form", "1011--1020"))
        item = self.tableWidget.item(19, 6)
        item.setText(_translate("Form", "2016"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setText(_translate("Form", "BibTeX from Google Scholars"))
 
if __name__ == '__main__':  
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow) 
    MainWindow.show()
    sys.exit(app.exec_()) 


